### ISSUE TITLE
PLOTS: If only one value then show only one value

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#12]
## Description

If there is only one survey value saved to the POD then only display one value in the charts. For example, the Systloic/Diastolic has one bar, centered along the x-axis. For the Weight, one single point, again centered along the x-axis.

![Image](https://github.com/kimishidairessha/diabetes/assets/1681429/ec460bcf-56c1-4c00-9e7a-c0647cb6a49c)

![Image](https://github.com/kimishidairessha/diabetes/assets/1681429/948f258d-b27c-49b7-84c7-2f2393a349bd)

**Comment by kimishidairessha** [comment]
Revise the issue where the value doesn't start at 0, as it confuses the user. Also, correct the error where the tooltip content is displayed when the user clicks on a date for which no survey has been filled out.
Example: When I click 20230820, it would be like:


![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/ff7db9a4-437d-4c13-b1e3-4843a3d56979)

The user will know that the entry was not filled in that day, rather than that the tooltip was not displayed because of a bug or because of an offset click.

**Comment by kimishidairessha** [comment]
Change the date format:


![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/a7bb4396-1725-470d-92a2-48eaa6c8b7d8)
