### ISSUE TITLE
SETTINGS: Add a setting to toggle Capture Location

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#50]
# Description

Add an option to the settings page to toggle Capture Location on and off, and also the frequency of capturing the location (default is 1 minute currently). Modify the saveGeoLocation() to immediately return if location capture is turned off.

Add a button to the MAP page to do the same, and keep the two in sync. Also allow the frequency to be set on the MAP page. 

# Why

The continuous location capture is not required. Turn it off by default.

# Closing Criteria

- [ ] Settings implementation
- [ ] Map page implementation

**Comment by kimishidairessha** [comment]
Add toggled to capture location and set location capture frequency on Setting page. When switch off, Pod will not get the location info and location will not be checked. Not sure if we need to add the same functionality to the MAP page. Because I think the duplication is a little redundant.



![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/1af98192-9ea3-45cb-8691-461ec108a058)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/49d9c343-be65-4534-ae2c-33c7220114a1)

**Comment by gjwgit** [comment]
Yes, duplication not a good idea. Let's just keep it in the settings. Thanks.

**Comment by kimishidairessha** [comment]
Detect on the debugger:


![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/df18070a-e421-4df5-929d-1e1b1e9a5fba)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/7c5b142b-5261-4127-8984-93c814174423)
